### ISSUE TITLE
In Progress Notebook:  Catching Supernovae with Neural Nets   

### ISSUE THREAD

**Issue by michaelJwilson** [michaelJwilson/desihigh#20]

**Comment by michaelJwilson** [comment]
@sybenzvi @eyu22 @alxogm  

I've added a new supernovae searching with transients notebook.  This lifts heavily from the notebooks @sybenzvi kindly put together, although I may a fair number of changes to match with the style / emphasis of elsewhere. 

@eyu22  It'd be great if you could take a look and let us know where things are unclear, or you'd like more emphasis.  Any suggestions welcome. 

@alxogm Thoughts welcome.  Assuming @sybenzvi @eyu22 are happy then we'll need a Spanish version.

@sybenzvi  A technical point:  the network training is _really_ slow on Binder, in a way I haven't seen in any other processing.  I'm curious if there's any ideas for what we might tweak, beyond the epoch number, that might help with this.

As nersc is down, and we're approaching Christmas, I'm trying to force an opportunity to get the Berkeley Extensions course set up.  We'll see how successful that is.

**Comment by michaelJwilson** [comment]
Replace with spectra from the Open Supernova Catalog:

SN1984L: https://sne.space/sne/SN1984L/
SN1987A: https://sne.space/sne/SN1987A/
SN1987M: https://sne.space/sne/SN1987M/
SN1987N only seems to have UV and radio photometry, but here is a Type Ia observe from that period pretty close to max light: https://sne.space/sne/SN1981B/

other TODOs remaining in notebook, e.g. plot on time scales.

**Comment by eyu22** [comment]
Hello, I hope you all have been having a wonderful week!

I just have a quick question about what a "data shape" is, as it was first mentioned on line 19 in the "DESI Bright Galaxy Survey" section. I don't really have a statistics background (yet), and was wondering what the line `hdus['FLUX'].data.shape`
 does and what the two numbers it returns `(6, 6265)` mean.

As for the machine learning section, I really like the diagram of the neuron and the chart of the neural network - it really helps build that visual connection between machine learning layers and neurons of the human brain.  Maybe this is getting too much into the technical, nitty gritty side of things, but what is thresholding exactly? The description in the notebook makes it so fascinating, the way it can result in almost limitless possibilities from a limited number of neurons, that I want to know a bit more about it. Why and how does that happen? Please correct me if I'm wrong, but in the neural network, is this caused by the how one tiny change in the input would impact all of the "hidden layers" it has to travel through before reaching the output layer?

Also, I was a bit curious as to what weights and biases are, so I did a bit of Googling and saw a few videos breaking down neural networks. I feel that this one especially:[ https://www.youtube.com/watch?v=aircAruvnKk]( https://www.youtube.com/watch?v=aircAruvnKk) did the best job in dissecting a neural network piece by piece in a way that someone who has no background at all in machine learning (like me) could understand. This is just a suggestion, but I think that this video would be a really useful link to add to the notebook just to offer that extra bit of knowledge to people who are curious. Otherwise, I think a few sentences explaining weights and biases could be extremely helpful too.

Lastly, I just wanted to say that this notebook is truly mind-bending. Just  reading the first few paragraphs inspired me to do more research into this topic, and though I only have a basic, skeletal understanding of deep learning right now, I'm really excited to learn more! I've always heard so much about how deep learning will be the "next big thing" of the future, so I'm super excited to see this notebook in the repository. Thank you so much @sybenzvi and @michaelJwilson for putting this together and I wish you all happy holidays!

**Comment by michaelJwilson** [comment]
@eyu22 This is great, thank you!  Hope you're having a great holiday.  

> I just have a quick question about what a "data shape" is, as it was first mentioned on line 19 in the "DESI Bright Galaxy Survey" section. I don't really have a statistics background (yet), and was wondering what the line hdus['FLUX'].data.shape
> does and what the two numbers it returns (6, 6265) mean.
Perfectly reasonable, in this case it refers to the shape of the matrix (or array).  E.g. you might record the number of breaths you take on every day or a year, and might record as elements of integers, e.g. 50, of a (24, 365) array.    

> thresholding exactly? The description in the notebook makes it so fascinating, the way it can result in almost limitless possibilities from a limited number of neurons, that I want to know a bit more about it. Why and how does that happen? Please correct me if I'm wrong, but in the neural network, is this caused by the how one tiny change in the input would impact all of the "hidden layers" it has to travel through before reaching the output layer?
Given you've been reading about it, you might have come across types of activation functions already, e.g. relu ( https://machinelearningmastery.com/rectified-linear-activation-function-for-deep-learning-neural-networks/)

Thresholding in this case was meant to imply that there's some range of input signals, e.g. from high energy to low energy, but in terms of output either a signal is sent out or its not, i.e. analog to digital.  I'll try and touch it up to make it clearer!  

Sounds great.  I'll add the video providing we're not breaking any copyrights in the future ;) there's lots of great material out there. 

I think you've been through all the current notebooks now, otherwise let me know if there's comments on any others!  Thanks again.

**Comment by michaelJwilson** [comment]
@eyu22 Thanks for the comments!  I updated the text to fill in the blanks that you highlighted. 

We'll have a new notebook by the end of the month, and will soon officially sign an agreement with UC Berkeley to make it an actual course, stay tuned.  We have a few science festival events coming up, let me know if you're interested in joining in (as staff or student).  Stay safe!

**Comment by eyu22** [comment]
@michaelJwilson That's exciting news, congratulations! The updated notebook looks amazing. 

And thanks for keeping me in the loop, I'd love to join in the upcoming science festivals. Let me know if there's anything I can help with in the meantime!
